#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication python3 setEmpty.py

runApplication setFields

# runApplication $FOAM_USER_APPBIN/$(getApplication)

runApplication decomposePar

runParallel $FOAM_USER_APPBIN/$(getApplication)

runApplication reconstructPar


#------------------------------------------------------------------------------
